---

- name: Install Apache
  yum: name=httpd state=latest

- name: Stop httpd
  service: name=httpd state=stopped

- name: Configure Apache httpd
  template: src=httpd.conf dest=/etc/httpd/conf/
  notify: restart httpd

- name: Restart httpd
  service: name=httpd state=restarted

- name: wait for httpd to start
  wait_for: port=80

